name: Deploy Website

on:
  push:
    branches:
      - main  # أي push على الفرع الرئيسي

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # ----------------------------
    # 1️⃣ Checkout code
    # ----------------------------
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        sparse-checkout: "./website"

    # ----------------------------
    # 2️⃣ Configure AWS CLI
    # ----------------------------
    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # ----------------------------
    # 3️⃣ Sync website to S3
    # ----------------------------
    - name: Sync website to S3
      run: |
        aws s3 sync ./website s3://my-tf-s3-with-cicd --delete

    # ----------------------------
    # 4️⃣ Invalidate CloudFront Cache
    # ----------------------------
    - name: CloudFront Invalidation
      run: |
        aws cloudfront create-invalidation \
          --distribution-id E27SAOA9KJ2V6V \
          --paths "/*"

  
   
